### ISSUE TITLE
Allow feeding in a 'light ID' instead of a pin number for the status LED

### ISSUE THREAD

**Issue by oliv3r** [hberntsen/mhi-ac-ctrl-esp32-c3#10]
It would be much nicer if we would use a id(light) instead of pin for the status led. This would allow us to use the onboard `status_led` (if configured) e.g.

```yaml
light:
  - platform: status_led
    name: "Status LED"
    id: board_status_led
    pin:
      number: GPIO02
      ignore_strapping_warning: true
    entity_category: diagnostic
```

But also a regular LED (e.g. not the status_led), if an additional LED is available.

This would allow for keeping the configuration in the high-level ESPHome yaml file instead.

**Comment by oliv3r** [comment]
You misunderstand :)

The status led is indeed a common esphome function, however you currently have
```yaml
status_led:
  pin:
    #white led, off when all good
    number: 19
```

Instead, if we could tell MHI-AC-Ctrl to use 'id(status_led)` we could use a single led for multiple functions (e.g. when WiFi is not connected, it's blinking, if the API is not connected, it's blinking. If MHI-AC-Ctrl says things are not okay ... it could be blinking.

```
The status_led light platform allows to share a single LED for indicating the status of the device (when on error/warning state) or as binary light (when on OK state). This is useful for devices with only one LED available. You can also use a binary [Output Component](https://esphome.io/components/output/#output).
```

But being able to use any `id(light)` as status_led input to MHI-ctrl, we could configure a regular GPIO output as LED, and tell MHI-AC-Ctrl to use that intead. I'm not sure if you can have several `status_led`'s or if they all blink in sync as you can only have one `status_led` and the others would need to be 'regular lights'

**Comment by hberntsen** [comment]
Ah, I see. In my units, the module is hidden inside the AC unit. If I turn on the LED, I can barely see it. After running for over more than a year, the only problem I encountered is related to the WiFi signal. Frame errors are very rare, it just works.

You could use the frame errors sensor to trigger an LED, i.e. do a

```
    frame_errors:
      name: ${device_name} Frame errors
      on_value_range:
        - above: 10
          then:
            - switch.turn_on: error led
```

Would that cover your use case?
