### ISSUE TITLE
Question: wifi and BLE together 

### ISSUE THREAD

**Issue by glsf91** [hberntsen/mhi-ac-ctrl-esp32-c3#2]
I added the original question again to make it more readable :-)

 I have the software up and running with a D1 mini esp32 (without using the CS lines). So it can run on the original mhs-ac-ctrl PCB. You wrote you have used this software with 8 BLE temp sensors.
 Did also have Wifi and MQTT active in this config?
 Because when I add esp32_ble_tracker to my config, the esp boots and resets right away. Without wifi and MQTT BLE is working.
 
Edit:
It is working now again. Resets are gone.

**Comment by hberntsen** [comment]
I am using those settings without issues:

```
esp32:
  board: esp32-c3-devkitm-1
  framework: 
    type: esp-idf
    sdkconfig_options: 
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y


esp32_ble_tracker:
  scan_parameters:
    active: false

sensor:
  - platform: pvvx_mithermometer
    mac_address: "aa:bb:cc:dd:ee:ff"
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    battery_level:
      name: "Battery-Level"
    battery_voltage:
      name: "Battery-Voltage"
    signal_strength:
      name: "Signal"
```

Though I'm not using MQTT, just the API connection to Home Assistant.

I see you closed the issue, I just wanted to share my configuration
anyway.
