### ISSUE TITLE
Trying a Atom S3 lite with your code

### ISSUE THREAD

**Issue by ebbenberg** [hberntsen/mhi-ac-ctrl-esp32-c3#7]
Hi.

I am trying your code on a Atom S3 lite

I have connected the following pins

```
MhiAcCtrl:
  id: ${mhi_device_id}
  # Optional PIN config
  # The default values are:
  mosi_pin: GPIO38
  miso_pin: GPIO39
  sclk_pin: GPIO8
  cs_in_pin: GPIO16
  cs_out_pin: GPIO15
```

However i get  Snapshot timeout errors.

I am sure mosi, miso and sclk pins are correct, as i used them with ginkage code of mhi-ac-ctrl code, and i can control the unit.

Do i need to use the cs in and out pins? Is it possible to do without?
As i dont know if the problems lies in that configuration  (gpio is also not know for the atom s3 lite on those pins)

Many thanks
